# Generated by Django 5.0.6 on 2024-08-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='field_of_study',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
