# Generated by Django 5.0.6 on 2024-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_field_of_study_student_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
