# Generated by Django 5.0.6 on 2024-08-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_category_rename_location_student_shelve_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
